# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XG5XsUJ2mJxm4keD-NlOT_ulj7p3lCML
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print(sns.get_dataset_names())

dataset=sns.load_dataset('car_crashes')
dataset

"""Histogram of Total Car Crashes:

In this histogram, we can see that the most common range for total car crashes is approximately between 10,000 and 15,000 crashes, with a peak around 12,000 crashes.
The distribution is right-skewed, indicating that a majority of states have lower total car crash counts, but a few states have significantly higher crash counts.
"""

# Example 1: Histogram of the number of car crashes
plt.figure(figsize=(8, 6)
sns.histplot(dataset['total'], bins=20, kde=True)
plt.xlabel('Total Car Crashes')
plt.ylabel('Frequency')
plt.title('Histogram of Total Car Crashes')
plt.show()

"""Scatter Plot between Alcohol Consumption and Speeding:

The scatter plot shows a weak positive correlation between alcohol consumption and the percentage of speeding-related accidents.
This suggests that in states with higher alcohol consumption rates, there tends to be a slightly higher percentage of accidents caused by speeding.
"""

# Example 2: Scatter plot between alcohol consumption and speeding
plt.figure(figsize=(8, 6))
sns.scatterplot(x='alcohol', y='speeding', data=dataset)
plt.xlabel('Alcohol Consumption')
plt.ylabel('Speeding (%)')
plt.title('Scatter Plot between Alcohol Consumption and Speeding')
plt.show()

"""Box Plot of Car Crashes by Insurance Premium:

The box plot illustrates the distribution of total car crashes across different insurance premium levels.
States with lower insurance premiums generally have a wider range of total crashes, including both low and high counts.
States with higher insurance premiums have a more consistent range of total crashes, with fewer outliers.
"""

# Example 3: Box plot of car crashes by insurance premium
plt.figure(figsize=(8, 6))
sns.boxplot(x='ins_premium', y='total', data=dataset)
plt.xlabel('Insurance Premium')
plt.ylabel('Total Car Crashes')
plt.title('Box Plot of Car Crashes by Insurance Premium')
plt.xticks(rotation=45)
plt.show()

"""Pairplot (Multiple Variable Relationships):

The pairplot provides a comprehensive view of relationships between multiple variables in the dataset.
Notable patterns include a positive correlation between 'total' car crashes and 'alcohol' consumption, as well as a negative correlation between 'total' car crashes and 'ins_premium.'
"""

sns.pairplot(dataset)
plt.show()

"""Bar Plot of Average Car Crashes by State (Abbreviation):

This bar plot displays the average total car crashes for each state, represented by their abbreviations.
States like 'DC' (District of Columbia) and 'RI' (Rhode Island) have notably higher average crash counts compared to other states.
Conversely, 'ND' (North Dakota) and 'VT' (Vermont) have lower average crash counts.
"""

plt.figure(figsize=(10, 6))
sns.barplot(x='abbrev', y='total', data=dataset)
plt.xlabel('State Abbreviation')
plt.ylabel('Average Total Car Crashes')
plt.title('Average Car Crashes by State')
plt.xticks(rotation=90)
plt.show()

"""The pairplot shows scatterplots and histograms for the numeric variables. It appears that there is a positive correlation between 'alcohol' and 'speeding,' while 'not_distracted' and 'no_previous' show some patterns of negative correlation with 'total' car crashes."""

sns.pairplot(dataset[['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous']])
plt.show()

"""This bar plot displays the average insurance premium for each state. It can help identify variations in insurance premiums across different states."""

plt.figure(figsize=(10, 6))
sns.barplot(x='abbrev', y='ins_premium', data=dataset)
plt.xlabel('State Abbreviation')
plt.ylabel('Average Insurance Premium')
plt.title('Average Insurance Premium by State')
plt.xticks(rotation=90)
plt.show()

"""The histogram of insurance losses shows the distribution of insurance losses across the dataset. It may reveal any predominant ranges of insurance losses."""

plt.figure(figsize=(8, 6))
sns.histplot(dataset['ins_losses'], bins=20, kde=True)
plt.xlabel('Insurance Losses')
plt.ylabel('Frequency')
plt.title('Histogram of Insurance Losses')
plt.show()

"""This box plot helps visualize the distribution of total car crashes based on the 'not_distracted' variable. It can highlight any differences in crash counts between distracted and not distracted states."""

plt.figure(figsize=(8, 6))
sns.boxplot(x='not_distracted', y='total', data=dataset)
plt.xlabel('Not Distracted')
plt.ylabel('Total Car Crashes')
plt.title('Box Plot of Car Crashes by Not Distracted')
plt.xticks(rotation=45)
plt.show()

"""This scatter plot explores the relationship between alcohol consumption and insurance premiums. It may indicate whether there is any connection between these two variables."""

plt.figure(figsize=(8, 6))
sns.scatterplot(x='alcohol', y='ins_premium', data=dataset)
plt.xlabel('Alcohol Consumption')
plt.ylabel('Insurance Premium')
plt.title('Scatter Plot between Alcohol Consumption and Insurance Premium')
plt.show()

""" we've created a pie chart to visualize the distribution of states in your dataset based on their abbreviations. The chart displays the proportion of each state relative to the total number of states in the dataset."""

state_counts = dataset['abbrev'].value_counts()

# Create a pie chart
plt.figure(figsize=(8, 8))
plt.pie(state_counts, labels=state_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Distribution of States in the Dataset')
plt.show()